import { StreamLanguage } from '@codemirror/language';
import { javascript } from '@codemirror/lang-javascript';
import { json } from '@codemirror/lang-json';
import { markdown } from '@codemirror/lang-markdown';
import { python } from '@codemirror/lang-python';
import { css as cssMode } from '@codemirror/legacy-modes/mode/css';
import { xml } from '@codemirror/legacy-modes/mode/xml';
import { rust } from '@codemirror/legacy-modes/mode/rust';
import { go } from '@codemirror/legacy-modes/mode/go';
import { c, cpp, csharp, java } from '@codemirror/legacy-modes/mode/clike';
export interface LanguagePack {
  id: string;
  name: string;
  version: string;
  exts: string[];
  color: string;
  blurb: string;
  runtimeId: string;
  frameworks: string[];
  libraries: string[];
  keywords: string[];
}
const jsKeywords = [
  'const',
  'let',
  'var',
  'function',
  'return',
  'class',
  'extends',
  'import',
  'export',
  'from',
  'async',
  'await',
  'new',
  'this',
  'if',
  'else',
  'for',
  'while',
  'switch',
  'case',
  'break',
  'continue',
  'try',
  'catch',
  'finally',
  'throw',
  'typeof',
  'instanceof',
  'of',
  'in',
  'true',
  'false',
  'null',
  'undefined',
];
export const LANGUAGE_PACKS: LanguagePack[] = [
  {
    id: 'typescript',
    name: 'TypeScript',
    version: 'built in',
    exts: ['.ts', '.mts', '.cts', '.tsx'],
    color: '#3178c6',
    runtimeId: 'node',
    blurb: 'Typed JavaScript with built-in highlighting, folding and completion.',
    frameworks: ['React', 'Next.js', 'Angular', 'NestJS'],
    libraries: ['Zod', 'Vitest', 'Prisma', 'tRPC'],
    keywords: [
      ...jsKeywords,
      'interface',
      'type',
      'enum',
      'implements',
      'readonly',
      'abstract',
      'namespace',
      'declare',
      'satisfies',
      'keyof',
      'unknown',
      'never',
    ],
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    version: 'built in',
    exts: ['.js', '.jsx', '.mjs', '.cjs'],
    color: '#f7df1e',
    runtimeId: 'node',
    blurb: 'Browser and Node.js development with syntax support ready immediately.',
    frameworks: ['React', 'Vue', 'Svelte', 'Express'],
    libraries: ['Vite', 'Jest', 'Axios', 'Three.js'],
    keywords: jsKeywords,
  },
  {
    id: 'python',
    name: 'Python',
    version: 'built in',
    exts: ['.py'],
    color: '#3776ab',
    runtimeId: 'python',
    blurb: 'Python editor support is built in; the runtime is detected from your system.',
    frameworks: ['Django', 'FastAPI', 'Flask'],
    libraries: ['NumPy', 'pandas', 'PyTorch', 'pytest'],
    keywords: [
      'def',
      'class',
      'return',
      'import',
      'from',
      'as',
      'if',
      'elif',
      'else',
      'for',
      'while',
      'try',
      'except',
      'finally',
      'raise',
      'with',
      'yield',
      'lambda',
      'None',
      'True',
      'False',
      'and',
      'or',
      'not',
      'in',
      'is',
      'pass',
      'async',
      'await',
      'self',
      'print',
      'range',
      'len',
    ],
  },
  {
    id: 'rust',
    name: 'Rust',
    version: 'built in',
    exts: ['.rs'],
    color: '#dea584',
    runtimeId: 'rust',
    blurb: 'Rust grammar and completion are included with Luma.',
    frameworks: ['Axum', 'Actix Web', 'Rocket', 'Bevy'],
    libraries: ['Tokio', 'Serde', 'Clap', 'Rayon'],
    keywords: [
      'fn',
      'let',
      'mut',
      'const',
      'struct',
      'enum',
      'impl',
      'trait',
      'pub',
      'use',
      'mod',
      'crate',
      'match',
      'if',
      'else',
      'loop',
      'while',
      'for',
      'in',
      'return',
      'async',
      'await',
      'unsafe',
      'Some',
      'None',
      'Ok',
      'Err',
    ],
  },
  {
    id: 'go',
    name: 'Go',
    version: 'built in',
    exts: ['.go'],
    color: '#00add8',
    runtimeId: 'go',
    blurb: 'Go syntax support is built in; Luma checks whether the Go toolchain exists.',
    frameworks: ['Gin', 'Fiber', 'Echo'],
    libraries: ['Cobra', 'GORM', 'Testify', 'Zap'],
    keywords: [
      'func',
      'package',
      'import',
      'var',
      'const',
      'type',
      'struct',
      'interface',
      'map',
      'chan',
      'go',
      'defer',
      'select',
      'switch',
      'case',
      'if',
      'else',
      'for',
      'range',
      'return',
      'true',
      'false',
      'nil',
    ],
  },
  {
    id: 'cpp',
    name: 'C / C++',
    version: 'built in',
    exts: ['.c', '.h', '.cpp', '.cc', '.cxx', '.hpp'],
    color: '#f34b7d',
    runtimeId: 'cpp',
    blurb: 'C and C++ highlighting is included; compiler availability is detected.',
    frameworks: ['Qt', 'SDL', 'Unreal'],
    libraries: ['Boost', 'OpenGL', 'Catch2', 'GoogleTest'],
    keywords: [
      'int',
      'char',
      'bool',
      'float',
      'double',
      'void',
      'const',
      'static',
      'class',
      'struct',
      'enum',
      'template',
      'namespace',
      'using',
      'public',
      'private',
      'new',
      'delete',
      'return',
      'if',
      'else',
      'for',
      'while',
      'switch',
      'try',
      'catch',
      'auto',
      'nullptr',
    ],
  },
  {
    id: 'java',
    name: 'Java',
    version: 'built in',
    exts: ['.java'],
    color: '#e76f00',
    runtimeId: 'java',
    blurb: 'Java editor support is included; JVM availability is reported separately.',
    frameworks: ['Spring', 'Quarkus', 'Micronaut', 'Android'],
    libraries: ['JUnit', 'Hibernate', 'Jackson', 'Guava'],
    keywords: [
      'public',
      'private',
      'protected',
      'class',
      'interface',
      'extends',
      'implements',
      'static',
      'final',
      'void',
      'int',
      'String',
      'new',
      'return',
      'if',
      'else',
      'for',
      'while',
      'switch',
      'try',
      'catch',
      'import',
      'package',
      'null',
      'true',
      'false',
    ],
  },
  {
    id: 'csharp',
    name: 'C#',
    version: 'built in',
    exts: ['.cs'],
    color: '#68217a',
    runtimeId: 'dotnet',
    blurb: 'C# editor support is included; Luma detects the installed .NET SDK.',
    frameworks: ['ASP.NET Core', 'Blazor', 'Unity', 'MAUI'],
    libraries: ['Entity Framework', 'xUnit', 'NUnit', 'Serilog'],
    keywords: [
      'using',
      'namespace',
      'class',
      'struct',
      'interface',
      'record',
      'public',
      'private',
      'static',
      'readonly',
      'void',
      'int',
      'string',
      'bool',
      'var',
      'new',
      'return',
      'if',
      'else',
      'foreach',
      'switch',
      'try',
      'catch',
      'async',
      'await',
      'null',
      'true',
      'false',
    ],
  },
];
export const DEFAULT_INSTALLED = LANGUAGE_PACKS.map((pack) => pack.id);
export function keywordsFor(path: string, _installed: string[] = DEFAULT_INSTALLED): string[] {
  const lower = path.toLowerCase();
  return (
    LANGUAGE_PACKS.find((pack) => pack.exts.some((ext) => lower.endsWith(ext)))?.keywords ?? []
  );
}
export function langSupport(
  path: string,
  _installed: string[]
): import('@codemirror/state').Extension[] {
  const lower = path.toLowerCase();
  if (lower.endsWith('.tsx')) return [javascript({ typescript: true, jsx: true })];
  if (lower.endsWith('.jsx')) return [javascript({ jsx: true })];
  if (/\.(ts|mts|cts)$/.test(lower)) return [javascript({ typescript: true })];
  if (/\.(js|mjs|cjs)$/.test(lower)) return [javascript()];
  if (lower.endsWith('.py')) return [python()];
  if (lower.endsWith('.rs')) return [StreamLanguage.define(rust)];
  if (lower.endsWith('.go')) return [StreamLanguage.define(go)];
  if (lower.endsWith('.java')) return [StreamLanguage.define(java)];
  if (lower.endsWith('.cs')) return [StreamLanguage.define(csharp)];
  if (/\.(cpp|cc|cxx|hpp)$/.test(lower)) return [StreamLanguage.define(cpp)];
  if (/\.(c|h)$/.test(lower)) return [StreamLanguage.define(c)];
  if (lower.endsWith('.json')) return [json()];
  if (/\.(md|markdown)$/.test(lower)) return [markdown()];
  if (lower.endsWith('.css')) return [StreamLanguage.define(cssMode)];
  if (/\.(html|htm|svg|xml)$/.test(lower)) return [StreamLanguage.define(xml)];
  return [];
}
export function fileBadge(path: string): { label: string; color: string } {
  const ext = /\.([a-z0-9]+)$/.exec(path.toLowerCase())?.[1] ?? '';
  const table: Record<string, { label: string; color: string }> = {
    ts: { label: 'TS', color: '#3178c6' },
    tsx: { label: 'TSX', color: '#3178c6' },
    mts: { label: 'TS', color: '#3178c6' },
    js: { label: 'JS', color: '#f7df1e' },
    jsx: { label: 'JSX', color: '#f7df1e' },
    mjs: { label: 'JS', color: '#f7df1e' },
    json: { label: '{ }', color: '#a3be8c' },
    md: { label: 'MD', color: '#94a3b8' },
    css: { label: 'CSS', color: '#38bdf8' },
    html: { label: '<>', color: '#e34f26' },
    py: { label: 'PY', color: '#3776ab' },
    rs: { label: 'RS', color: '#dea584' },
    go: { label: 'GO', color: '#00add8' },
    java: { label: 'JV', color: '#e76f00' },
    cs: { label: 'C#', color: '#68217a' },
    c: { label: 'C', color: '#f34b7d' },
    cpp: { label: 'C++', color: '#f34b7d' },
    h: { label: 'H', color: '#f34b7d' },
    yml: { label: 'YML', color: '#cbccc6' },
    yaml: { label: 'YML', color: '#cbccc6' },
    lock: { label: 'LCK', color: '#cbccc6' },
    sh: { label: 'SH', color: '#89e051' },
    png: { label: 'IMG', color: '#a074c4' },
    jpg: { label: 'IMG', color: '#a074c4' },
    svg: { label: 'SVG', color: '#ffb13b' },
  };
  return table[ext] ?? { label: '·', color: '#6b7280' };
}
