import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildExtendedStackCommands, runExtendedStackToolAction } from '../src/main/extendedStackTools';
import { ensureCargoManifest, ensureDotnetManifest, ensureGoManifest } from '../src/main/stackManifestPreparation';
import { completeStackToolStatus, runCompleteStackToolAction } from '../src/main/completeStackTools';
import { isStackToolSupported, stackToolDefinition } from '../src/shared/stackCatalog';
import { LANGUAGE_PACKS } from '../src/renderer/src/languages';
function tool(packId: string, name: string) { const definition = stackToolDefinition(packId, name); if (!definition) throw new Error(`Missing test definition: ${packId}:${name}`); return definition; }
describe('complete Stack catalog', () => {
  it('gives every visible framework and library an approved action', () => { for (const pack of LANGUAGE_PACKS) for (const name of [...pack.frameworks, ...pack.libraries]) expect(stackToolDefinition(pack.id, name), `${pack.id}:${name}`).toBeDefined(); });
  it('builds fixed Windows launcher commands without renderer text', () => { expect(buildExtendedStackCommands(tool('csharp', 'Unity'), 'install', 'win32')[0]).toMatchObject({ command: 'winget.exe', args: ['install', '--id', 'Unity.UnityHub', '--exact', '--source', 'winget', '--accept-package-agreements', '--accept-source-agreements', '--disable-interactivity'] }); expect(buildExtendedStackCommands(tool('cpp', 'Unreal'), 'uninstall', 'win32')[0].args).toEqual(['uninstall', '--id', 'EpicGames.EpicGamesLauncher', '--exact', '--source', 'winget', '--disable-interactivity']); });
  it('keeps proprietary launcher actions Windows-only', () => { expect(isStackToolSupported(tool('csharp', 'Unity'), 'linux')).toBe(false); expect(() => buildExtendedStackCommands(tool('cpp', 'Unreal'), 'install', 'linux')).toThrow('not available'); });
  it('builds version-pinned .NET and workload commands', () => { expect(buildExtendedStackCommands(tool('csharp', 'ASP.NET Core'), 'install', 'win32', 'Sample.csproj')[0]).toMatchObject({ command: 'dotnet', args: ['add', 'Sample.csproj', 'package', 'Microsoft.AspNetCore.OpenApi', '--version', '8.0.30'] }); expect(buildExtendedStackCommands(tool('csharp', 'MAUI'), 'uninstall', 'linux')[0]).toMatchObject({ command: 'dotnet', args: ['workload', 'uninstall', 'maui'] }); });
});
describe('manifest-backed Stack actions', () => {
  it('adds, detects, and removes Maven dependencies', async () => { const repo = await mkdtemp(join(tmpdir(), 'luma-maven-')); try { const installed = await runCompleteStackToolAction(repo, 'install', 'java', 'Spring', 'linux'); expect(installed.output).toContain('Created a minimal pom.xml'); expect(await readFile(join(repo, 'pom.xml'), 'utf8')).toContain('<artifactId>spring-context</artifactId>'); expect((await completeStackToolStatus(repo, 'linux'))['java:Spring']).toBe(true); await runCompleteStackToolAction(repo, 'uninstall', 'java', 'Spring', 'linux'); expect(await readFile(join(repo, 'pom.xml'), 'utf8')).not.toContain('<artifactId>spring-context</artifactId>'); } finally { await rm(repo, { recursive: true, force: true }); } });
  it('adds, detects, and removes vcpkg dependencies', async () => { const repo = await mkdtemp(join(tmpdir(), 'luma-vcpkg-')); try { await runCompleteStackToolAction(repo, 'install', 'cpp', 'Qt', 'linux'); expect(JSON.parse(await readFile(join(repo, 'vcpkg.json'), 'utf8')).dependencies).toContain('qtbase'); expect((await completeStackToolStatus(repo, 'linux'))['cpp:Qt']).toBe(true); await runCompleteStackToolAction(repo, 'uninstall', 'cpp', 'Qt', 'linux'); expect(JSON.parse(await readFile(join(repo, 'vcpkg.json'), 'utf8')).dependencies).not.toContain('qtbase'); } finally { await rm(repo, { recursive: true, force: true }); } });
  it('does not overwrite malformed manifests', async () => { const repo = await mkdtemp(join(tmpdir(), 'luma-invalid-')); try { await writeFile(join(repo, 'vcpkg.json'), '{ not-json', 'utf8'); await expect(runExtendedStackToolAction(repo, 'install', 'Qt', tool('cpp', 'Qt'), 'linux')).rejects.toThrow('will not overwrite'); expect(await readFile(join(repo, 'vcpkg.json'), 'utf8')).toBe('{ not-json'); } finally { await rm(repo, { recursive: true, force: true }); } });
  it('creates Cargo, Go, and .NET manifests only when missing', async () => { const repo = await mkdtemp(join(tmpdir(), 'Luma Project ')); try { await expect(ensureCargoManifest(repo, 'install')).resolves.toContain('Cargo.toml'); await expect(ensureCargoManifest(repo, 'install')).resolves.toBeNull(); await expect(ensureGoManifest(repo, 'install')).resolves.toContain('go.mod'); await expect(ensureDotnetManifest(repo, 'install')).resolves.toContain('.csproj'); } finally { await rm(repo, { recursive: true, force: true }); } });
  it('rejects names outside the fixed catalog', async () => { await expect(runCompleteStackToolAction('/tmp/project', 'install', 'java', 'Spring && calc.exe', 'win32')).rejects.toThrow('not an approved Stack package'); });
});
